all: ex3.o path_finder.o
	
ex3.o: ex3.c /home/amit/Documents/cs2110/week2b/queue.c
	gcc -o ex3.o ex3.c /home/amit/Documents/cs2110/week2b/queue.c

path_finder.o: path_finder.c /home/amit/Documents/cs2110/week2b/queue.c
	gcc -o path_finder.o path_finder.c /home/amit/Documents/cs2110/week2b/queue.c
